### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by rahul-ka** [SneakyBastardSword/SantaBot#1]
Traceback (most recent call last):
  File "santa-bot.py", line 45, in <module>
    exchange_started = config['programData'].as_bool('exchange_started')
  File "C:\Python\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'programData'

**Comment by avchikar97** [comment]
To future users who wish to use this bot, I have fixed many of the bugs in the original repository. I have also added quite a few features. I would recommend pulling from [that fork](https://github.com/avchikar97/SantaBot) instead of having to reinvent the wheel (or the secret santa bot).
